on:
  push:
    branches: ["main"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Check Python Version
        run: python3 -V
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: pip-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip

      - name: install dependencies
        run: |
          python3 -m pip install pip --upgrade
          pip install -r requirements.txt

      - run: echo "Completed...!"