name: Condtion

on: 
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "$MYVAR"
        env: 
          MYVAR: ${{ toJson(github) }}

  job2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/karl'
    steps:
      - run: echo "$MYVAR"
        env: 
          MYVAR: ${{ toJson(github) }}