name: Condtion

on: 
  push:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: |
          echo "${{ vars.AWS_REGION }}"

  job2:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: |
          echo "${{ vars.AWS_REGION }}"
            