name: Deploy

on: 
  push:
  pull_request:

vars:
  AWS_ECR_REPO_NAME: flask-app
  AWS_ECS_CLUSTER_NAME: 'NA'
  AWS_ECS_SERVICE_NAME: 'NA'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - name: Download the files
        uses: actions/checkout@v4

      - name: Login to ECR
        id: ecr-data
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Build the image
      #   run: |
      #     docker build -t myapp .

      - name: Print ECR Repo URI
        run: echo "${{ steps.ecr-data.outputs.registry }}"
