name: CICD-Pipeline
on: # Triggers
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: |
          docker ps 
          echo "hello" > abc.txt
          sleep 10
        
      - name: check the file
        run: |
          ls -la
          sleep 15
        
      - run: |
          echo "Karl"
          cat abc.txt
        name: multi line bash script
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: create a file
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_REGION_NAME=$AWS_REGION_NAME
          aws iam list-users
          echo "Your applcation has been deployed"
          sleep 35
      
      - run: echo "hello"


  
