name: Test Workflow

on:
  push:
    # branches: []

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - run: echo "hello" > abc.txt
      - run: ls -l 

  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l   
